// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5vkyaF73lJRLLDnrolzDpFHhAWaILGEA',
    appId: '1:382670272012:web:4be228364135c737f32029',
    messagingSenderId: '382670272012',
    projectId: 'unilink-97ccb',
    authDomain: 'unilink-97ccb.firebaseapp.com',
    storageBucket: 'unilink-97ccb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmER54B6AXP1YADOpZwTZ7wtmSLHkIt9I',
    appId: '1:382670272012:android:410d632cb0d4409bf32029',
    messagingSenderId: '382670272012',
    projectId: 'unilink-97ccb',
    storageBucket: 'unilink-97ccb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsSDWgFWJsP7VZWjSkPBKkCAn1WWXO0Ps',
    appId: '1:382670272012:ios:d2894ca3ce649649f32029',
    messagingSenderId: '382670272012',
    projectId: 'unilink-97ccb',
    storageBucket: 'unilink-97ccb.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsSDWgFWJsP7VZWjSkPBKkCAn1WWXO0Ps',
    appId: '1:382670272012:ios:d2894ca3ce649649f32029',
    messagingSenderId: '382670272012',
    projectId: 'unilink-97ccb',
    storageBucket: 'unilink-97ccb.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5vkyaF73lJRLLDnrolzDpFHhAWaILGEA',
    appId: '1:382670272012:web:ca5a7fa06b6554a0f32029',
    messagingSenderId: '382670272012',
    projectId: 'unilink-97ccb',
    authDomain: 'unilink-97ccb.firebaseapp.com',
    storageBucket: 'unilink-97ccb.firebasestorage.app',
  );
}
